"""
Currency code to country name mapping.
"""

CURRENCY_COUNTRIES = {
    'AED': 'United Arab Emirates',
    'AFN': 'Afghanistan',
    'ALL': 'Albania',
    'AMD': 'Armenia',
    'ANG': 'Netherlands Antilles (Curaçao, Sint Maarten)',
    'AOA': 'Angola',
    'ARS': 'Argentina',
    'AUD': 'Australia',
    'AWG': 'Aruba',
    'AZN': 'Azerbaijan',
    'BAM': 'Bosnia and Herzegovina',
    'BBD': 'Barbados',
    'BDT': 'Bangladesh',
    'BGN': 'Bulgaria',
    'BHD': 'Bahrain',
    'BIF': 'Burundi',
    'BMD': 'Bermuda',
    'BND': 'Brunei',
    'BOB': 'Bolivia',
    'BRL': 'Brazil',
    'BSD': 'Bahamas',
    'BTN': 'Bhutan',
    'BWP': 'Botswana',
    'BYN': 'Belarus',
    'BZD': 'Belize',
    'CAD': 'Canada',
    'CDF': 'Democratic Republic of the Congo',
    'CHF': 'Switzerland',
    'CLF': 'Chile (Unidad de Fomento)',
    'CLP': 'Chile',
    'CNH': 'China (Offshore Yuan)',
    'CNY': 'China',
    'COP': 'Colombia',
    'CRC': 'Costa Rica',
    'CUP': 'Cuba',
    'CVE': 'Cape Verde',
    'CZK': 'Czech Republic',
    'DJF': 'Djibouti',
    'DKK': 'Denmark',
    'DOP': 'Dominican Republic',
    'DZD': 'Algeria',
    'EGP': 'Egypt',
    'ERN': 'Eritrea',
    'ETB': 'Ethiopia',
    'EUR': 'European Union',
    'FJD': 'Fiji',
    'FKP': 'Falkland Islands',
    'FOK': 'Faroe Islands',
    'GBP': 'United Kingdom',
    'GEL': 'Georgia',
    'GGP': 'Guernsey',
    'GHS': 'Ghana',
    'GIP': 'Gibraltar',
    'GMD': 'Gambia',
    'GNF': 'Guinea',
    'GTQ': 'Guatemala',
    'GYD': 'Guyana',
    'HKD': 'Hong Kong',
    'HNL': 'Honduras',
    'HRK': 'Croatia',
    'HTG': 'Haiti',
    'HUF': 'Hungary',
    'IDR': 'Indonesia',
    'ILS': 'Israel',
    'IMP': 'Isle of Man',
    'INR': 'India',
    'IQD': 'Iraq',
    'IRR': 'Iran',
    'ISK': 'Iceland',
    'JEP': 'Jersey',
    'JMD': 'Jamaica',
    'JOD': 'Jordan',
    'JPY': 'Japan',
    'KES': 'Kenya',
    'KGS': 'Kyrgyzstan',
    'KHR': 'Cambodia',
    'KID': 'Kiribati',
    'KMF': 'Comoros',
    'KRW': 'South Korea',
    'KWD': 'Kuwait',
    'KYD': 'Cayman Islands',
    'KZT': 'Kazakhstan',
    'LAK': 'Laos',
    'LBP': 'Lebanon',
    'LKR': 'Sri Lanka',
    'LRD': 'Liberia',
    'LSL': 'Lesotho',
    'LYD': 'Libya',
    'MAD': 'Morocco',
    'MDL': 'Moldova',
    'MGA': 'Madagascar',
    'MKD': 'North Macedonia',
    'MMK': 'Myanmar',
    'MNT': 'Mongolia',
    'MOP': 'Macau',
    'MRU': 'Mauritania',
    'MUR': 'Mauritius',
    'MVR': 'Maldives',
    'MWK': 'Malawi',
    'MXN': 'Mexico',
    'MYR': 'Malaysia',
    'MZN': 'Mozambique',
    'NAD': 'Namibia',
    'NGN': 'Nigeria',
    'NIO': 'Nicaragua',
    'NOK': 'Norway',
    'NPR': 'Nepal',
    'NZD': 'New Zealand',
    'OMR': 'Oman',
    'PAB': 'Panama',
    'PEN': 'Peru',
    'PGK': 'Papua New Guinea',
    'PHP': 'Philippines',
    'PKR': 'Pakistan',
    'PLN': 'Poland',
    'PYG': 'Paraguay',
    'QAR': 'Qatar',
    'RON': 'Romania',
    'RSD': 'Serbia',
    'RUB': 'Russia',
    'RWF': 'Rwanda',
    'SAR': 'Saudi Arabia',
    'SBD': 'Solomon Islands',
    'SCR': 'Seychelles',
    'SDG': 'Sudan',
    'SEK': 'Sweden',
    'SGD': 'Singapore',
    'SHP': 'Saint Helena',
    'SLE': 'Sierra Leone',
    'SLL': 'Sierra Leone (Old)',
    'SOS': 'Somalia',
    'SRD': 'Suriname',
    'SSP': 'South Sudan',
    'STN': 'São Tomé and Príncipe',
    'SYP': 'Syria',
    'SZL': 'Eswatini (Swaziland)',
    'THB': 'Thailand',
    'TJS': 'Tajikistan',
    'TMT': 'Turkmenistan',
    'TND': 'Tunisia',
    'TOP': 'Tonga',
    'TRY': 'Turkey',
    'TTD': 'Trinidad and Tobago',
    'TVD': 'Tuvalu',
    'TWD': 'Taiwan',
    'TZS': 'Tanzania',
    'UAH': 'Ukraine',
    'UGX': 'Uganda',
    'USD': 'United States',
    'UYU': 'Uruguay',
    'UZS': 'Uzbekistan',
    'VES': 'Venezuela',
    'VND': 'Vietnam',
    'VUV': 'Vanuatu',
    'WST': 'Samoa',
    'XAF': 'Central African CFA (CEMAC)',
    'XCD': 'Eastern Caribbean',
    'XCG': 'Caribbean Guilder',
    'XDR': 'IMF Special Drawing Rights',
    'XOF': 'West African CFA (WAEMU)',
    'XPF': 'CFP Franc (French Pacific)',
    'YER': 'Yemen',
    'ZAR': 'South Africa',
    'ZMW': 'Zambia',
    'ZWG': 'Zimbabwe (Gold)',
    'ZWL': 'Zimbabwe',
}

def get_country_for_currency(currency_code: str) -> str:
    """
    Get country name for a currency code.
    
    Args:
        currency_code: Currency code (e.g., 'USD', 'EUR')
        
    Returns:
        Country name or currency code if not found
    """
    return CURRENCY_COUNTRIES.get(currency_code.upper(), currency_code)

